[package]
name = "aptos-api"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos REST API"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
bcs = "0.1.2"
bytes = "1.0.1"
fail = "0.4.0"
futures = "0.3.12"
futures-util = "0.3"
hex = "0.4.3"
hyper = "0.14.4"
once_cell = "1.7.2"
percent-encoding = "2.1.0"
serde = { version = "1.0.124", features = ["derive"], default-features = false }
serde_json = "1.0.64"
tokio = { version = "1.8.1", features = ["full"] }
tokio-stream = "0.1.8"
warp = { version = "0.3.2", features = ["default", "tls"] }

aptos-config = { path = "../config" }
aptos-crypto = { path = "../crates/aptos-crypto" }
aptos-logger = { path = "../crates/aptos-logger" }
aptos-mempool = { path = "../mempool"}
aptos-metrics = { path = "../crates/aptos-metrics" }
aptos-state-view = { path = "../storage/state-view" }
aptos-types = { path = "../types" }
aptos-vm = { path = "../aptos-move/aptos-vm" }
aptos-workspace-hack = { version = "0.1", path = "../crates/aptos-workspace-hack" }
aptos-api-types = { path = "./types", package = "aptos-api-types" }
storage-interface = { path = "../storage/storage-interface" }
move-core-types = { git = "https://github.com/move-language/move", rev = "43f1e151dea91ca8e8c7644557e55b8f456fbb65", features=["address32"] }
move-resource-viewer = { git = "https://github.com/move-language/move", rev = "43f1e151dea91ca8e8c7644557e55b8f456fbb65" }

[dev-dependencies]
goldenfile = "1.1.0"
rand = "0.8.3"
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }

aptos-crypto = { path = "../crates/aptos-crypto" }
aptos-genesis-tool = {path = "../config/management/genesis", features = ["testing"] }
aptos-global-constants = { path = "../config/global-constants" }
aptos-mempool = { path = "../mempool", features = ["fuzzing"] }
aptos-sdk = { path = "../sdk" }
aptos-secure-storage = { path = "../secure/storage" }
aptos-temppath = { path = "../crates/aptos-temppath" }
aptos-vm = { path = "../aptos-move/aptos-vm" }
aptosdb = { path = "../storage/aptosdb", features = ["fuzzing"] }
cached-framework-packages = { path = "../aptos-move/framework/cached-packages" }
executor = { path = "../execution/executor" }
executor-types = { path = "../execution/executor-types" }
mempool-notifications = { path = "../state-sync/inter-component/mempool-notifications" }
vm-validator = { path = "../vm-validator" }

[features]
failpoints = ["fail/failpoints"]
